### ISSUE TITLE
Issues notifications

### ISSUE THREAD

**Issue by reysonk** [uPagge/gitlab-notification#20]
Прошу  рассмотреть возможность добавить функционал уведомлений Issues

- Уведомление о новых Issues
- Уведомление об обновлении Issues
- Уведомление об изменении статуса Issues
- Уведомление о новых тегах Issues
- Уведомление при упоминаниях в комментариях Issues
- Уведомления при ответах в дискуссии Issues, в которой вы писали

p.s : Почти год жду после статьи на [хабре](https://habr.com/ru/post/649889/) :)

> Также планирую добавить поддержку уведомлений по Issue, мы на проектах пользуемся Jira, но мне не сложно :)

**Comment by webparadoxer** [comment]
И я бы хотел вообще видеть, activity-log)

**Comment by uPagge** [comment]
Привет
Все помню, но времени не было. Сейчас вроде график посвободнее и нашлись желающие развивать проект, так что в ближайшее время займемся. Пока проводим рефакторинг, а потом сразу к новым фичам))

**Comment by ridouchire** [comment]
Привет. Ожидать ли таковую функциональность в будущем?
